"""fix_models_final

Revision ID: 8bc2bf2e1fcc
Revises: 3ebd933536e3
Create Date: 2026-07-22 14:22:53.363240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8bc2bf2e1fcc'
down_revision: Union[str, None] = '3ebd933536e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_quotes')
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=True)
    op.alter_column('invoices', 'total',
               existing_type=sa.NUMERIC(precision=14, scale=2),
               type_=sa.Numeric(precision=15, scale=2),
               nullable=True)
    op.drop_index('ix_invoices_client_id', table_name='invoices')
    op.drop_index('ix_invoices_folio', table_name='invoices')
    op.drop_index('ix_invoices_quote_id', table_name='invoices')
    op.drop_constraint('invoices_quote_id_fkey', 'invoices', type_='foreignkey')
    op.drop_constraint('invoices_client_id_fkey', 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'paid_amount')
    op.drop_column('invoices', 'pdf_url')
    op.drop_column('invoices', 'quote_id')
    op.drop_column('invoices', 'exchange_rate')
    op.drop_column('invoices', 'folio')
    op.drop_column('invoices', 'iva_amount')
    op.drop_column('invoices', 'balance')
    op.drop_column('invoices', 'client_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('client_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('balance', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('iva_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('folio', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('invoices', sa.Column('exchange_rate', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('quote_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('pdf_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('invoices', sa.Column('paid_amount', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=False))
    op.create_foreign_key('invoices_client_id_fkey', 'invoices', 'legal_entities', ['client_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key('invoices_quote_id_fkey', 'invoices', 'quotes', ['quote_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_invoices_quote_id', 'invoices', ['quote_id'], unique=False)
    op.create_index('ix_invoices_folio', 'invoices', ['folio'], unique=True)
    op.create_index('ix_invoices_client_id', 'invoices', ['client_id'], unique=False)
    op.alter_column('invoices', 'total',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.alter_column('invoices', 'subtotal',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.NUMERIC(precision=14, scale=2),
               nullable=False)
    op.create_table('invoice_quotes',
    sa.Column('invoice_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('quote_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='invoice_quotes_invoice_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], name='invoice_quotes_quote_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id', 'quote_id', name='invoice_quotes_pkey')
    )
    # ### end Alembic commands ###