"""fix_models_final

Revision ID: efe60747bcc1
Revises: 8bc2bf2e1fcc
Create Date: 2026-07-22 14:23:03.617614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'efe60747bcc1'
down_revision: Union[str, None] = '8bc2bf2e1fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###