"""corporate_id_nullable

Revision ID: 0e8368145860
Revises: fc13231dd94c
Create Date: 2026-05-14 01:40:42.265132

"""
from typing import Sequence, Union



revision: str = '0e8368145860'
down_revision: Union[str, None] = 'fc13231dd94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###