"""add missing index and FK on invoices.client_id

Revision ID: a861c2bc2f9d
Revises: efe60747bcc1
Create Date: 2026-08-24 16:26:35.009226

"""
from typing import Sequence, Union

from alembic import op


revision: str = 'a861c2bc2f9d'
down_revision: Union[str, None] = 'efe60747bcc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_folio'), 'invoices', ['folio'], unique=False)
    op.create_foreign_key(None, 'invoices', 'legal_entities', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_folio'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    # ### end Alembic commands ###