"""add_invoice_quotes

Revision ID: caa9ec852cdd
Revises: f848a2941d24
Create Date: 2026-06-26 18:14:39.944590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'caa9ec852cdd'
down_revision: Union[str, None] = 'f848a2941d24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_quotes',
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('invoice_id', 'quote_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_quotes')
    # ### end Alembic commands ###