"""add_quotes

Revision ID: d3b4b79a31f2
Revises: 0e8368145860
Create Date: 2026-05-14 06:28:27.084262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd3b4b79a31f2'
down_revision: Union[str, None] = '0e8368145860'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('legal_entities_corporate_id_fkey', 'legal_entities', type_='foreignkey')
    op.create_foreign_key(None, 'legal_entities', 'corporates', ['corporate_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'legal_entities', type_='foreignkey')
    op.create_foreign_key('legal_entities_corporate_id_fkey', 'legal_entities', 'corporates', ['corporate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###