"""add_exchange_rate

Revision ID: f848a2941d24
Revises: 07569f681a46
Create Date: 2026-06-26 10:58:55.756562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f848a2941d24'
down_revision: Union[str, None] = '07569f681a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('quotes', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotes', 'exchange_rate')
    op.drop_column('invoices', 'exchange_rate')
    # ### end Alembic commands ###